language: scala
scala:
  - 2.11.7

before_script:
  # Init xvfb for headless browser testing
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Start test server
  - cd test/server && npm install && node index.js &

script:
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION scalaHttpJS/test
  - sbt ++$TRAVIS_SCALA_VERSION scalaHttpJVM/test
  - sbt ++$TRAVIS_SCALA_VERSION firefox:test
